import ServiceDetail from '../../src/components/ServiceDetail';
const PLANS = [
  { nameEn: 'AI Boost', nameAr: 'تعزيز الذكاء', price: '399', planKey: 'AI_Boost', descEn: 'Essential AI-assisted content for startups.', descAr: 'محتوى أساسي مدعوم بالذكاء الاصطناعي للمشاريع الناشئة.', features: [{ en: '10 AI-Driven Posts / Articles', ar: '١٠ منشورات أو مقالات ذكية' }, { en: 'Smart Keyword Research', ar: 'بحث كلمات مفتاحية مدعوم بالـ AI' }, { en: '100% Human Fact-Checking', ar: 'مراجعة وتدقيق بشري ١٠٠٪' }, { en: 'Plagiarism & AI Detection Check', ar: 'فحص الانتحال وكشف الذكاء الاصطناعي' }] },
  { nameEn: 'Content Scale', nameAr: 'مقياس المحتوى', price: '799', planKey: 'AI_Scale', featured: true, badgeEn: 'Fastest Growth', badgeAr: 'النمو الأسرع', descEn: 'High-volume content production for active brands.', descAr: 'إنتاج محتوى بحجم كبير للمواقع والعلامات النشطة.', features: [{ en: '30 AI-Optimized SEO Articles', ar: '٣٠ مقالاً محسناً بالـ AI للسيو' }, { en: 'Custom AI Visual Generation', ar: 'توليد صور حصرية بالذكاء الاصطناعي' }, { en: 'Automated Social Scheduling', ar: 'جدولة تلقائية لمنصات التواصل' }, { en: 'Fast 48h Turnaround per Batch', ar: 'تسليم سريع خلال ٤٨ ساعة' }] },
  { nameEn: 'Enterprise AI', nameAr: 'ذكاء المؤسسات', price: '1,499', planKey: 'AI_Enterprise', descEn: 'Custom AI trained specifically on your brand voice.', descAr: 'نماذج ذكاء اصطناعي مدربة خصيصاً على نبرة صوت علامتك.', features: [{ en: 'Custom AI Model Prompt Tuning', ar: 'تدريب نموذج AI مخصص لنبرة شركتك' }, { en: 'Unlimited AI Content Generation', ar: 'توليد محتوى ذكي غير محدود' }, { en: 'Full Brand Integration', ar: 'دمج كامل مع هوية العلامة التجارية' }] },
];
export default function AiContentPage() {
  return <ServiceDetail titleEn="AI Content Optimization" titleAr="المحتوى بالذكاء الاصطناعي" descEn="Scale your content with AI. We merge human creativity with artificial intelligence to produce high-quality content faster than ever." descAr="ضاعف محتواك بالذكاء الاصطناعي. ندمج الإبداع البشري مع قوة التقنية لإنتاج محتوى عالي الجودة بسرعة فائقة." image="/assets/img/hero/ai.jpg" metaDesc="استخدام الذكاء الاصطناعي لإنتاج محتوى رقمي متميز بسرعة وكفاءة عالية." features={[{ titleEn: 'AI Writing', titleAr: 'الكتابة الذكية', descEn: 'Optimized for SEO', descAr: 'محتوى محسن لمحركات البحث' }, { titleEn: 'Data Analysis', titleAr: 'تحليل البيانات', descEn: 'Smart insights', descAr: 'رؤى وتحليلات ذكية' }, { titleEn: 'Fast Turnaround', titleAr: 'سرعة التنفيذ', descEn: 'Time-saving delivery', descAr: 'تسليم فوري موفر للوقت' }]} pricingTitleEn="AI Content Plans" pricingTitleAr="باقات الذكاء الاصطناعي" plans={PLANS} />;
}
