import ServiceDetail from '../../src/components/ServiceDetail';
const PLANS = [
  { nameEn: 'Identity Core', nameAr: 'أساس الهوية', price: '299', planKey: 'Brand_Core', descEn: 'Essential branding for startups.', descAr: 'أساسيات الهوية للشركات الناشئة والمشاريع الجديدة.', features: [{ en: 'Primary Logo Design (3 Concepts)', ar: 'تصميم الشعار الأساسي (٣ أفكار)' }, { en: 'Brand Color Palette', ar: 'لوحة الألوان الخاصة بالعلامة' }, { en: 'Typography Selection', ar: 'اختيار الخطوط المتناسقة' }, { en: 'Basic Logo Usage Guidelines', ar: 'دليل أساسي لاستخدام الشعار' }] },
  { nameEn: 'Business Identity', nameAr: 'هوية الشركات', price: '699', planKey: 'Brand_Business', featured: true, badgeEn: 'Highly Recommended', badgeAr: 'نوصي بها', descEn: 'Complete visual language for growing companies.', descAr: 'لغة بصرية كاملة وشاملة لعملك واحتياجاتك التسويقية.', features: [{ en: 'Full Logo Suite', ar: 'مجموعة الشعارات الكاملة' }, { en: 'Corporate Stationery Design', ar: 'تصميم المطبوعات' }, { en: 'Social Media Brand Kit', ar: 'هوية وقوالب حسابات التواصل الاجتماعي' }, { en: 'Brand Guideline Book (Mini)', ar: 'دليل استخدام الهوية' }] },
  { nameEn: 'Legacy Brand', nameAr: 'باقة الإرث', price: '1,499', planKey: 'Brand_Legacy', descEn: 'Strategic branding & full guidelines for enterprises.', descAr: 'بناء استراتيجي ودليل شامل للهوية للشركات الكبرى.', features: [{ en: 'Brand Strategy & Positioning Workshop', ar: 'ورشة عمل لبناء استراتيجية العلامة' }, { en: 'Extensive Visual Identity System', ar: 'نظام هوية بصرية متكامل وموسع' }, { en: 'Full Brand Guideline Book', ar: 'دليل هوية متكامل' }] },
];
export default function BrandingPage() {
  return <ServiceDetail titleEn="Visual Identity & Branding" titleAr="الهوية البصرية والعلامة التجارية" descEn="We don't just design logos; we build legacy. We create a visual language that reflects your values and speaks directly to your audience." descAr="نحن لا نصمم شعارات فحسب، بل نبني إرثاً. نخلق لغة بصرية تعكس قيمك وتتحدث مباشرة إلى جمهورك." image="/assets/img/hero/branding.jpg" metaDesc="هوية بصرية احترافية تميزك عن المنافسين وتترك أثراً لا يُنسى في ذهن عملائك." features={[{ titleEn: 'Logo Design', titleAr: 'تصميم الشعار', descEn: 'Iconic & Scalable', descAr: 'أيقوني وقابل للتوسع' }, { titleEn: 'Brand Voice', titleAr: 'صوت العلامة', descEn: 'Consistent communication', descAr: 'تواصل متسق وموحد' }, { titleEn: 'Visual Kit', titleAr: 'الحزمة البصرية', descEn: 'Complete brand assets', descAr: 'أصول بصرية متكاملة' }]} pricingTitleEn="Branding Packages" pricingTitleAr="باقات الهوية" plans={PLANS} />;
}
