import ServiceDetail from '../../src/components/ServiceDetail';
const PLANS = [
  { nameEn: 'Blog Power', nameAr: 'قوة التدوين', price: '299', planKey: 'Content_Blog', descEn: 'Boost your SEO with high-quality monthly blogs.', descAr: 'عزز السيو الخاص بك بمقالات شهرية عالية الجودة.', features: [{ en: '4 SEO-Optimized Articles', ar: '٤ مقالات محسنة وموافقة للسيو' }, { en: 'Keyword Integration', ar: 'دمج احترافي للكلمات المفتاحية' }, { en: 'Meta Title & Description', ar: 'كتابة العناوين ووصف الميتا' }, { en: 'Topic Research & Strategy', ar: 'بحث وتخطيط مواضيع المقالات' }] },
  { nameEn: 'Creative Copy', nameAr: 'الكتابة الإعلانية', price: '499', planKey: 'Content_Creative', featured: true, badgeEn: 'Best Value', badgeAr: 'الأكثر مبيعاً', descEn: 'High-converting sales copy for your campaigns.', descAr: 'نصوص إعلانية بيعية ترفع نسبة مبيعات حملاتك.', features: [{ en: '1 High-Converting Sales Page', ar: 'كتابة صفحة مبيعات (Landing Page)' }, { en: '10 Ad Copies (Social Media)', ar: '١٠ نصوص إعلانية للسوشيال' }, { en: 'Brand Voice Development', ar: 'تطوير نبرة صوت البراند' }, { en: 'A/B Hook Testing Variants', ar: 'عناوين لاختبار A/B' }] },
  { nameEn: 'Full Narrative', nameAr: 'المحتوى المتكامل', price: '899', planKey: 'Content_Narrative', descEn: 'Comprehensive brand storytelling and identity.', descAr: 'سرد قصصي متكامل لبناء هوية علامتك التجارية.', features: [{ en: 'Full Company Profile', ar: 'بروفايل شركة كامل' }, { en: '3 Video Scripts (AI & Promo)', ar: '٣ سيناريوهات فيديو احترافية' }, { en: 'Arabic & English Content', ar: 'محتوى باللغتين العربية والإنجليزية' }] },
];
export default function ContentWritingPage() {
  return <ServiceDetail titleEn="Professional Content Writing" titleAr="كتابة المحتوى الاحترافية" descEn="Content that converts. Our expert writers craft compelling narratives that resonate with your brand voice." descAr="محتوى يحقق النتائج. كتابنا الخبراء يصيغون قصصاً مقنعة تتوافق مع صوت علامتك التجارية." image="/assets/img/hero/content.jpg" metaDesc="محتوى يحول القراء إلى عملاء. فريق كتابة محترف لكل أنواع المحتوى الرقمي." features={[{ titleEn: 'Blogging', titleAr: 'المدونات', descEn: 'Thought leadership', descAr: 'ترسيخ ريادة الفكر' }, { titleEn: 'Copywriting', titleAr: 'الكتابة الإعلانية', descEn: 'Sales-driven text', descAr: 'نصوص موجهة للبيع' }, { titleEn: 'Scripts', titleAr: 'السيناريوهات', descEn: 'Video & Audio scripts', descAr: 'نصوص فيديو وصوت' }]} pricingTitleEn="Content Packages" pricingTitleAr="باقات المحتوى" plans={PLANS} />;
}
