import ServiceDetail from '../../src/components/ServiceDetail';
const PLANS = [
  { nameEn: 'Starter Store', nameAr: 'متجر البداية', price: '799', planKey: 'Store_Starter', descEn: 'Perfect for startups and small niche stores.', descAr: 'مثالي للمتاجر المتخصصة والمشاريع الناشئة.', features: [{ en: 'Standard CMS Setup (WooCommerce)', ar: 'إعداد متجر قياسي (ووكومرس)' }, { en: 'Secure Payment Gateways Setup', ar: 'تفعيل بوابات الدفع الإلكتروني' }, { en: 'Mobile Responsive Design', ar: 'تصميم متجاوب مع الموبايل' }, { en: 'User-Friendly Admin Panel', ar: 'لوحة تحكم سهلة لإدارة الطلبات' }] },
  { nameEn: 'Pro E-Commerce', nameAr: 'متجر احترافي', price: '1,499', planKey: 'Web_Ecommerce', featured: true, badgeEn: 'Most Popular', badgeAr: 'الأكثر طلباً', descEn: 'Full-scale scalable solution for high traffic & sales.', descAr: 'حل شامل وقابل للتوسع للمتاجر ذات الزيارات العالية.', features: [{ en: 'Advanced Custom Coding / Premium UI', ar: 'برمجة مخصصة / تصميم واجهات فاخر' }, { en: 'Logistics & Shipping API Integration', ar: 'ربط آلي مع شركات الشحن' }, { en: 'Advanced E-commerce SEO', ar: 'تحسين متقدم لمحركات البحث' }, { en: 'Multi-Language (EN/AR) & Currencies', ar: 'دعم لغتين وعملات متعددة' }, { en: 'Abandoned Cart Recovery System', ar: 'نظام استرجاع سلات المشتريات المتروكة' }] },
  { nameEn: 'Enterprise System', nameAr: 'نظام شركات كبرى', price: '3,499', planKey: 'Store_Enterprise', descEn: 'Custom ERP & comprehensive Inventory sync.', descAr: 'أنظمة مخصصة وربط كامل مع ERP والمخازن.', features: [{ en: 'Custom ERP & POS Integration', ar: 'ربط مخصص مع أنظمة ERP ونقاط البيع' }, { en: 'Dedicated DevOps & Hosting', ar: 'استضافة مخصصة وإدارة تقنية' }, { en: 'Priority 24/7 Support', ar: 'دعم أولوية على مدار الساعة' }] },
];
export default function EcommercePage() {
  return <ServiceDetail titleEn="E-commerce Solutions" titleAr="حلول التجارة الإلكترونية" descEn="Open your store to the world. We provide end-to-end e-commerce development with seamless payment and logistics integration." descAr="افتح متجرك للعالم. نوفر تطوير متاجر إلكترونية شاملة مع ربط سلس لبوابات الدفع والخدمات اللوجستية." image="/assets/img/hero/store.jpg" metaDesc="حلول تجارة إلكترونية متكاملة — من تصميم المتجر إلى ربط بوابات الدفع والشحن." features={[{ titleEn: 'Payment Gateways', titleAr: 'بوابات الدفع', descEn: 'Secure transactions', descAr: 'عمليات دفع آمنة' }, { titleEn: 'Product Management', titleAr: 'إدارة المنتجات', descEn: 'Easy inventory control', descAr: 'تحكم سهل في المخزون' }, { titleEn: 'Marketing Tools', titleAr: 'أدوات تسويقية', descEn: 'Built-in coupons & SEO', descAr: 'كوبونات وسيو مدمج' }]} pricingTitleEn="Store Packages" pricingTitleAr="باقات المتاجر" plans={PLANS} />;
}
