import ServiceDetail from '../../src/components/ServiceDetail';
const PLANS = [
  { nameEn: 'Starter', nameAr: 'البداية', price: '499', planKey: 'Ads_Starter', descEn: 'For small businesses testing ads.', descAr: 'للشركات الصغيرة أو لتجربة إعلاناتك الأولى.', features: [{ en: 'Manage 1 Platform', ar: 'إدارة منصة إعلانية واحدة' }, { en: 'Up to 2 Campaigns / Month', ar: 'حتى حملتين شهرياً' }, { en: 'Ad Creation & Copywriting', ar: 'إنشاء الإعلانات وكتابة المحتوى' }, { en: 'Audience Targeting Setup', ar: 'إعداد وتحديد استهداف الجمهور' }, { en: 'Basic Performance Report', ar: 'تقرير أداء أساسي' }] },
  { nameEn: 'Growth', nameAr: 'النمو', price: '999', planKey: 'Ads_Growth', featured: true, badgeEn: 'Grow Faster', badgeAr: 'نمو أسرع', descEn: 'Aiming for leads and sales.', descAr: 'لزيادة العملاء المحتملين أو مضاعفة المبيعات.', features: [{ en: 'Manage 2 Platforms', ar: 'إدارة منصتين إعلانيتين' }, { en: 'Up to 5 Campaigns / Month', ar: 'حتى ٥ حملات إعلانية شهرياً' }, { en: 'Audience Retargeting Setup', ar: 'إعداد حملات إعادة الاستهداف' }, { en: 'A/B Testing for Best Results', ar: 'اختبار A/B للوصول لأفضل أداء' }, { en: 'Monthly Performance Report', ar: 'تقرير أداء وتحليل تفصيلي شهرياً' }] },
  { nameEn: 'Elite VIP', nameAr: 'النخبة VIP', price: '1,899', planKey: 'Ads_Elite', descEn: 'Established brands, maximum results.', descAr: 'للعلامات التجارية الكبرى لأقصى النتائج.', features: [{ en: 'Manage 3 Platforms', ar: 'إدارة ٣ منصات إعلانية' }, { en: '5+ Campaigns / Month', ar: '+٥ حملات إعلانية شهرياً' }, { en: 'Creative Designs Included', ar: 'تصاميم إبداعية مضمنة' }, { en: 'Advanced Funnel Optimization', ar: 'تحسين متقدم لمسارات التحويل' }, { en: 'Priority Support', ar: 'دعم أولوية' }] },
];
export default function PaidAdsPage() {
  return <ServiceDetail titleEn="Paid Advertising (PPC)" titleAr="الإعلانات الممولة" descEn="Get immediate results. Our targeted ad campaigns are designed to maximize ROI and lower customer acquisition costs." descAr="احصل على نتائج فورية. حملاتنا الإعلانية المستهدفة مصممة لتعظيم عائد الاستثمار وتقليل تكلفة جذب العملاء." image="/assets/img/hero/ads.jpg" metaDesc="حملات إعلانية ممولة احترافية على جوجل وميتا وتيك توك تحقق أقصى عائد على الاستثمار." features={[{ titleEn: 'Search Ads', titleAr: 'إعلانات البحث', descEn: 'Be on top of Google', descAr: 'كن في مقدمة جوجل' }, { titleEn: 'Social Ads', titleAr: 'إعلانات التواصل', descEn: 'Meta & TikTok ads', descAr: 'إعلانات ميتا وتيك توك' }, { titleEn: 'Conversion Tracking', titleAr: 'تتبع التحويل', descEn: 'Analyze every cent', descAr: 'حلل كل قرش تنفقه' }]} pricingTitleEn="Ad Campaigns Plans" pricingTitleAr="باقات الإعلانات" plans={PLANS} />;
}
